### ISSUE TITLE
Exception NullPointerException

### ISSUE THREAD

**Issue by DevSrSouza** [Guichaguri/MinimalFTP#2]
```
Exception in thread "Thread-97" java.lang.NullPointerException
   at com.guichaguri.minimalftp.FTPConnection.sendResponse(FTPConnection.java:198)
   at com.guichaguri.minimalftp.FTPConnection.processCommand(FTPConnection.java:519)
   at com.guichaguri.minimalftp.FTPConnection.process(FTPConnection.java:444)
   at com.guichaguri.minimalftp.FTPConnection.update(FTPConnection.java:556)
   at com.guichaguri.minimalftp.FTPConnection$ConnectionThread.run(FTPConnection.java:603)
```

**Comment by Guichaguri** [comment]
That was caused because a command was throwing an unknown exception with a null message, I don't know which one though
